version: "3.1"

services:
  dolphinscheduler-postgresql:
    image: bitnami/postgresql:15.2.0
    environment:
      TZ: Asia/Shanghai
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: dolphinscheduler
    volumes:
      - dolphinscheduler-postgresql:/bitnami/postgresql
    networks:
      - dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-zookeeper:
    image: bitnami/zookeeper:3.7.1
    environment:
      TZ: Asia/Shanghai
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons
    volumes:
      - dolphinscheduler-zookeeper:/bitnami/zookeeper
    networks:
      - dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-api:
    image: apache/dolphinscheduler-api
    ports:
      - 12345:12345
      - 25333:25333
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:12345/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - dolphinscheduler-shared-local:/opt/soft
      - dolphinscheduler-resource-local:/dolphinscheduler
    networks:
      - dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-alert:
    image: apache/dolphinscheduler-alert-server
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:50053/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
    networks:
      - dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-master:
    image: apache/dolphinscheduler-master
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:50053/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - dolphinscheduler-shared-local:/opt/soft
    networks:
      - dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1

  dolphinscheduler-worker:
    image: apache/dolphinscheduler-worker
    env_file: .env
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:50053/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - dolphinscheduler-worker-data:/tmp/dolphinscheduler
      - dolphinscheduler-logs:/opt/dolphinscheduler/logs
      - dolphinscheduler-shared-local:/opt/soft
      - dolphinscheduler-resource-local:/dolphinscheduler
    networks:
      - dolphinscheduler
    deploy:
      mode: replicated
      replicas: 1

networks:
  dolphinscheduler:
    driver: overlay

volumes:
  dolphinscheduler-postgresql:
  dolphinscheduler-zookeeper:
  dolphinscheduler-worker-data:
  dolphinscheduler-logs:
  dolphinscheduler-shared-local:
  dolphinscheduler-resource-local: